yatube/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),

]   

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
namespace = 'posts'

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),

]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
        )
    group = models.ForeignKey(
        'Group',
        on_delete=models.CASCADE,
        blank=True,
        null=True
        ) 
    

class Group(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    slug = models.SlugField(unique=True)
        
    def __str__(self):
        return self.title
    

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse
from .models import Post, Group

# Главная страница
#def index(request):    
#    template = loader.get_template('posts/index.html')
#    title = "Это главная страница проекта Yatube"
#    context = {
#        'title': title
#              }
#    return HttpResponse(template.render(context, request)) 

def index(request):
    title = "Это главная страница проекта Yatube"
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 

def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    title = group.title
    context = {
        'group': group,
        'posts': posts,
        'title': title
    }
    return render(request, 'posts/group_list.html', context) 

# view-функция принимает параметр pk из path()
#def group_posts(request, slug):
#    template = loader.get_template('posts/group_list.html')

#    group = get_object_or_404(Group, slug=slug)

#    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
#    context = {
#        'group': group,
#        'posts': posts,
#    }
#    return HttpResponse(template.render(context, request)) 









    

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
<head>    
  <meta charset="utf-8"> <!-- Кодировка сайта -->
  <!-- Сайт готов работать с мобильными устройствами -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Загружаем фав-иконки -->
  <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <!-- Подключен файл со стандартными стилями бустрап -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{% block titleup %}{% endblock %}</title>
</head>
  <body>
    <header>
       {% include 'includes/header.html' %}     
    </header>
    <main> 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>{% block title %}{% endblock %}</h1>
            {% block content %}{% endblock %}
        <!-- под последним постом нет линии -->
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}   
    </footer>
  </body>

yatube/templates/includes/footer.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Последние обновления на сайте</title>
  </head>       
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>

yatube/templates/includes/header.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->

    <!-- <link rel="icon" href="img/fav/favicon.ico" type="image">-->
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Последние обновления на сайте</title>
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>      
    </header>
  </body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block titleup %}Группа{% endblock %}

{% block title %}
      Записи сообщества "{{ title }}"
{% endblock %}  

{% block content %}

{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>    
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block titleup %} {{ title }} {% endblock %}

{% block title %}
      Последние обновления на сайте
{% endblock %}  

{% block content %}
<article>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li>
      Группа: {{ post.group.title }}
    </li>
  </ul>
  <p>{{ post.text }}</p>  

  <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
</article>  
{% endblock %}  